[[plugins]]
package = "@netlify/plugin-nextjs"

[[edge_functions]]
function = "edge-cache"
path = "/varied"
excludedPath = ["/_next/*"]

[[edge_functions]]
function = "edge-cache"
path = "/cookie"
excludedPath = ["/_next/*"]

[dev]
targetPort = 3000
edge_functions = "netlify/edge-functions"
functions = "netlify/functions"
excludedPath = ["/_next/*"]

[build]
publish = ".next"
edge_functions = "netlify/edge-functions"
functions = "netlify/functions"
excludedPath = ["/_next/*"]
