[[plugins]]
package = "@netlify/plugin-nextjs"

[function]
node_bundler = "esbuild"

[[edge_functions]]
path = "/*"
function ="cache-edge"

[dev]
targetPort = 3000
edge_functions = "netlify/edge-functions"
functions = "netlify/functions"
excludedPath = ["/_next/*"]

[build]
publish = ".next"
edge_functions = "netlify/edge-functions"
functions = "netlify/functions"
excludedPath = ["/_next/*"]
