import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import { TrpcClientProvider } from '../trpc/client/trpc-client-provider';
import { PageWrapper } from '../components/page-wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  search,
  children,
}: Readonly<{
  search: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrpcClientProvider headers={headers()}>
          <PageWrapper>
            {search}
            {children}
          </PageWrapper>
        </TrpcClientProvider>
      </body>
    </html>
  );
}
